name: Jaap Bakker
description: Blogging about life's challenges...
meta_description: "The blog of Jaap Bakker. Owner of Colorblind, receptionist at Rockstart and lively guy from Amsterdam."

markdown: redcarpet
highlighter: pygments
logo: assets/images/logo.png
paginate: 5
baseurl: /blog
domain_name: 'http://j33p.nl/blog'
google_analytics: 'UA-66706864-1'

# Details for the RSS feed generator
url:            'http://www.j33p.nl/blog'
author:         'Jaap Bakker'
author_description: 	'Ik woon in Amsterdam en schrijf al sinds jaar en dag.En daar hoort natuurlijk een blog bij. Nu meer <em>business-related</em>.'
